const defaults={whatsapp:'2348067278021',heroImage:'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=1000&q=85',serviceImage:'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1000&q=85',products:[
{name:'The Juno',category:'Wigs',price:85000,image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=700&q=85'},
{name:'Gold Rush Hoops',category:'Piercings',price:15000,image:'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=700&q=85'},
{name:'The Sade',category:'Wigs',price:120000,image:'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=700&q=85'},
{name:'Brow Sculpt Kit',category:'Beauty',price:18000,image:'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=700&q=85'}]};
const services=[['01','Lashes',' From  ₦18,000'],['02','Brow Sculpt & Tint', 'From  ₦12,000'],['03','make-up', 'From  ₦15,000'],['04','Fine-line Tattoos', 'From  ₦30,000']];
let state=JSON.parse(localStorage.getItem('ofab-world')||'null')||structuredClone(defaults);let cart=[];let active='All';let booking='';
const $=s=>document.querySelector(s);const money=n=>'₦'+n.toLocaleString('en-NG');
function render(){ $('#heroImage').src=state.heroImage;$('#serviceImage').src=state.serviceImage;let cats=['All',...new Set(state.products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button class="${active===c?'active':''}" data-filter="${c}">${c}</button>`).join('');let items=active==='All'?state.products:state.products.filter(p=>p.category===active);$('#products').innerHTML=items.map((p,i)=>`<article class="product"><div class="product-image"><img src="${p.image}" alt="${p.name}"><button class="add" data-add="${state.products.indexOf(p)}" aria-label="Add ${p.name}">+</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.category}</p></div><b class="price">${money(p.price)}</b></div></article>`).join('');$('#serviceList').innerHTML=services.map(s=>`<div class="service-item"><div><b>${s[0]}</b><span>${s[1]}<small>${s[2]}</small></span></div><button class="book-mini" data-book="${s[1]}">Book ↗</button></div>`).join('');}
function renderCart(){ $('#bagCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-line"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>${money(p.price)}</p></div><button class="remove" data-remove="${i}">×</button></div>`).join(''):'<p class="empty">Your bag is waiting for its first obsession.</p>';$('#total').textContent=money(cart.reduce((t,p)=>t+p.price,0));}
function openBooking(name,desc){booking=name;$('#bookingTitle').textContent=`Book ${name}`;$('#bookingDescription').textContent=desc||'Choose your preferred day and we’ll begin the conversation on WhatsApp.';$('#bookingDialog').showModal()}
function wa(text){let n=String(state.whatsapp).replace(/\D/g,'');if(!n||n==='2348067278021'){toast('Add the real owner WhatsApp number in Edit site first.');return}window.open(`https://wa.me/${n}?text=${encodeURIComponent(text)}`,'_blank','noopener');}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
document.addEventListener('click',e=>{let f=e.target.closest('[data-filter]');if(f){active=f.dataset.filter;render()}let a=e.target.closest('[data-add]');if(a){cart.push(state.products[a.dataset.add]);renderCart();toast('Added to your selection.')}let b=e.target.closest('[data-book]');if(b)openBooking(b.dataset.book);let r=e.target.closest('[data-remove]');if(r){cart.splice(r.dataset.remove,1);renderCart()}let close=e.target.closest('[data-close]');if(close){let el=close.dataset.close==='cart'?$('#cart'):$('#'+close.dataset.close);el.close?el.close():el.classList.remove('open');$('#overlay').classList.remove('open')};});
$('#bagButton').onclick=()=>{$('#cart').classList.add('open');$('#overlay').classList.add('open')};$('#overlay').onclick=()=>{$('#cart').classList.remove('open');$('#overlay').classList.remove('open')};$('#checkout').onclick=()=>{if(!cart.length)return toast('Choose something from the collection first.');wa(`Hello OFab Beauty World! I would love to order:\n${cart.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n')}\n\nTotal: ${money(cart.reduce((t,p)=>t+p.price,0))}`)};
$('#agreeBooking').onclick=()=>{let date=$('#bookingDate').value||'not selected';let note=$('#bookingNote').value.trim()||'No extra notes';wa(`Hello OFab World! I would like to book *${booking}*.\nPreferred date: ${date}\nNotes: ${note}`);$('#bookingDialog').close()};
$('#openEditor').onclick=()=>{let f=$('#editorForm');f.whatsapp.value=state.whatsapp;f.heroImage.value=state.heroImage;f.serviceImage.value=state.serviceImage;f.products.value=state.products.map(p=>`${p.name} | ${p.category} | ${p.price} | ${p.image}`).join('\n');$('#editorDialog').showModal()};$('#editorForm').onsubmit=e=>{e.preventDefault();let f=e.target;let parsed=f.products.value.split('\n').filter(Boolean).map(line=>{let [name,category,price,image]=line.split('|').map(x=>x.trim());return{name,category,price:Number(String(price).replace(/[^0-9.]/g,'')),image}}).filter(p=>p.name&&p.category&&p.price&&p.image);if(!parsed.length)return toast('Add at least one valid product.');state={whatsapp:f.whatsapp.value,heroImage:f.heroImage.value,serviceImage:f.serviceImage.value,products:parsed};localStorage.setItem('ofab-world',JSON.stringify(state));active='All';render();$('#editorDialog').close();toast('Your OFab World edits are live.');};$('#resetSite').onclick=()=>{localStorage.removeItem('ofab-world');state=structuredClone(defaults);active='All';render();$('#editorDialog').close();toast('Demo content restored.');};
render();renderCart();
